create table public.cart_items (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  game_id bigint null,
  game_key_id bigint null,
  user_id bigint null,
  constraint cart_items_pkey primary key (id),
  constraint cart_items_game_id_fkey foreign KEY (game_id) references games (id),
  constraint cart_items_game_key_id_fkey foreign KEY (game_key_id) references game_keys (id),
  constraint cart_items_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;