create table public.categories (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  description text null,
  cover text null,
  is_active boolean null,
  constraint categories_pkey primary key (id)
) TABLESPACE pg_default;