create table public.game_keys (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  key text null default ''::text,
  game_id bigint null,
  price double precision null,
  key_type text null,
  constraint game_keys_pkey primary key (id),
  constraint game_keys_game_id_fkey foreign KEY (game_id) references games (id)
) TABLESPACE pg_default;