create table public.games (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  description text null,
  cover text null,
  category_id bigint null,
  constraint games_pkey primary key (id),
  constraint games_category_id_fkey foreign KEY (category_id) references categories (id)
) TABLESPACE pg_default;