create table public.order (
  id bigint generated by default as identity not null,
  total_price bigint not null,
  user_id bigint null,
  status text null,
  comment text null,
  constraint order_pkey primary key (id),
  constraint order_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;