create table public.roles (
  id bigint generated by default as identity not null,
  name text not null,
  constraint roles_pkey primary key (id),
  constraint roles_name_key unique (name)
) TABLESPACE pg_default;