create table public.role_permissions (
  id bigint generated by default as identity not null,
  role_id bigint not null,
  granted_at timestamp with time zone not null default now(),
  premission text null,
  constraint role_permissions_pkey primary key (id),
  constraint role_permissions_role_id_fkey foreign KEY (role_id) references roles (id) on delete CASCADE
) TABLESPACE pg_default;