create table public.sub_orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  order_id bigint null,
  user_id bigint null,
  game_id bigint null,
  game_key_id bigint null,
  constraint sub_orders_pkey primary key (id),
  constraint sub_orders_game_id_fkey foreign KEY (game_id) references games (id),
  constraint sub_orders_game_key_id_fkey foreign KEY (game_key_id) references game_keys (id),
  constraint sub_orders_order_id_fkey foreign KEY (order_id) references "order" (id),
  constraint sub_orders_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;